services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && python main.py"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: "db"
    image: postgres:16-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  db_test:
    container_name: "db_test"
    image: postgres:16-bullseye
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"