"""empty message

Revision ID: 8b07b4906617
Revises: 
Create Date: 2024-03-04 16:00:55.814481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b07b4906617'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closing_status', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission', sa.String(length=100), nullable=False),
    sa.Column('line', sa.String(length=100), nullable=False),
    sa.Column('shift', sa.String(length=100), nullable=False),
    sa.Column('crew', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('nomenclature', sa.String(length=100), nullable=False),
    sa.Column('single_cadastral_number', sa.String(length=100), nullable=False),
    sa.Column('work_center', sa.String(length=100), nullable=False),
    sa.Column('shift_start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'batch_date', name='u_number_date')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('is_aggregated', sa.Boolean(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('batch')
    # ### end Alembic commands ###
