"""empty message

Revision ID: 9512b34097da
Revises: 8b07b4906617
Create Date: 2024-03-05 14:03:44.012024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9512b34097da'
down_revision: Union[str, None] = '8b07b4906617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('batch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'batch', ['batch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'batch_id')
    # ### end Alembic commands ###
